# Generated by Django 5.1 on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("engine", models.CharField(default="piper", max_length=32)),
                (
                    "voice",
                    models.CharField(
                        default="fr_FR-upmc-medium", max_length=128
                    ),
                ),
                (
                    "tts_addr",
                    models.CharField(
                        default="pi4.local:8765", max_length=256
                    ),
                ),
            ],
            options={},
        ),
    ]
