# Generated by Django 6.0.5 on 2026-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_host', models.TextField(default='localhost')),
                ('broker_port', models.IntegerField(default=1883)),
                ('broker_username', models.TextField(default='', null=True)),
                ('broker_password', models.TextField(default='', null=True)),
                ('broker_tls', models.BooleanField(default=False)),
                ('device_id', models.TextField(default='', null=True)),
                ('discovery_prefix', models.TextField(default='homeassistant')),
                ('topic_prefix', models.TextField(default='nabaztag')),
                ('default_radio_url', models.TextField(default='', null=True)),
                ('json_data_base', models.TextField(default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
