# Generated by Django 5.1 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabairqualityd", "0008_alter_config_localisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="use_tts",
            field=models.BooleanField(default=False),
        ),
    ]
