# Generated by Django 5.1 on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabsurprised", "0002_alter_config_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="use_tts",
            field=models.BooleanField(default=False),
        ),
    ]
